'use client';

import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';

// 8 angle views generated by Flux + multi-image PuLID, same seed, same prompt,
// only the "angle" descriptor changes per view. Index 0 = front, increases
// clockwise as seen from above.
const FRAMES = [
    '/jeon_360_00.png',
    '/jeon_360_45.png',
    '/jeon_360_90.png',
    '/jeon_360_135.png',
    '/jeon_360_180.png',
    '/jeon_360_225.png',
    '/jeon_360_270.png',
    '/jeon_360_315.png',
];

/**
 * 360-degree photoreal "spin" viewer.
 *
 * Mouse X across the viewport maps to a frame index — left edge shows back-left,
 * right edge shows back-right. Idle auto-rotation when the cursor is still.
 * Only responsive while the visitor is on the landing viewport.
 *
 * This delivers the visual effect of a 3D spinning figure using real Flux
 * renders — no mesh artifacts, no stylization, photoreal end-to-end.
 */
export default function Hero360Viewer() {
    const [frameIdx, setFrameIdx] = useState(0);
    const mouseRef = useRef(0);        // -1 .. +1
    const idleRef = useRef(true);
    const onLandingRef = useRef(true);
    const lastMoveRef = useRef(0);
    const [enabled, setEnabled] = useState(true);

    useEffect(() => {
        const mediaSmall = window.matchMedia('(max-width: 767px)');
        const mediaReduce = window.matchMedia('(prefers-reduced-motion: reduce)');
        const decide = () => setEnabled(!mediaSmall.matches);
        decide();
        mediaSmall.addEventListener('change', decide);
        mediaReduce.addEventListener('change', decide);

        const onMouse = (e) => {
            mouseRef.current = (e.clientX / window.innerWidth) * 2 - 1;
            lastMoveRef.current = Date.now();
            idleRef.current = false;
        };
        const onScroll = () => {
            onLandingRef.current = window.scrollY < window.innerHeight * 0.85;
        };
        onScroll();
        window.addEventListener('mousemove', onMouse, { passive: true });
        window.addEventListener('scroll', onScroll, { passive: true });

        // Animation loop: pick which frame to show based on mouse X (when active)
        // or auto-rotate when idle. Cap frame updates to ~12 fps to avoid
        // image-element thrash.
        let raf = 0;
        let lastFrameTime = 0;
        let autoAngle = 0;
        const reduce = mediaReduce.matches;
        function tick() {
            const now = performance.now();
            if (now - lastFrameTime > 80) {
                lastFrameTime = now;
                const onLanding = onLandingRef.current;
                const idleNow = Date.now() - lastMoveRef.current > 1500;
                idleRef.current = idleNow;

                let targetIdx;
                if (onLanding && !idleNow) {
                    // Mouse -1..+1 -> 0..7 frames (8 angles around)
                    const t = (mouseRef.current + 1) / 2; // 0..1
                    targetIdx = Math.floor(t * FRAMES.length) % FRAMES.length;
                } else if (!reduce) {
                    // Idle / off-landing: slow auto-spin
                    autoAngle += 0.06;
                    targetIdx = Math.floor(autoAngle) % FRAMES.length;
                } else {
                    targetIdx = 0;
                }
                setFrameIdx(targetIdx);
            }
            raf = requestAnimationFrame(tick);
        }
        raf = requestAnimationFrame(tick);

        return () => {
            cancelAnimationFrame(raf);
            window.removeEventListener('mousemove', onMouse);
            window.removeEventListener('scroll', onScroll);
            mediaSmall.removeEventListener('change', decide);
            mediaReduce.removeEventListener('change', decide);
        };
    }, []);

    if (!enabled) return null;

    return (
        <div className="hero360-stack">
            {FRAMES.map((src, i) => (
                <Image
                    key={src}
                    src={src}
                    alt="Hyunsik Jeon"
                    width={520}
                    height={780}
                    priority={i === 0}
                    className={`hero360-frame${i === frameIdx ? ' is-visible' : ''}`}
                />
            ))}
            <div className="hero360-dots">
                {FRAMES.map((_, i) => (
                    <span
                        key={i}
                        className={`hero360-dot${i === frameIdx ? ' is-active' : ''}`}
                    />
                ))}
            </div>

            <style jsx>{`
                .hero360-stack {
                    position: relative;
                    width: 100%;
                    height: 100%;
                    overflow: hidden;
                    border-radius: 0.75rem;
                }
                :global(.hero360-frame) {
                    position: absolute;
                    inset: 0;
                    width: 100% !important;
                    height: 100% !important;
                    object-fit: cover;
                    opacity: 0;
                    transition: opacity 110ms linear;
                    will-change: opacity;
                }
                :global(.hero360-frame.is-visible) {
                    opacity: 1;
                }
                .hero360-dots {
                    position: absolute;
                    bottom: 0.75rem;
                    left: 50%;
                    transform: translateX(-50%);
                    display: flex;
                    gap: 0.375rem;
                    pointer-events: none;
                    z-index: 5;
                }
                .hero360-dot {
                    width: 5px;
                    height: 5px;
                    border-radius: 9999px;
                    background: rgba(255, 255, 255, 0.3);
                    transition: background 0.25s ease, transform 0.25s ease;
                }
                .hero360-dot.is-active {
                    background: #fff;
                    transform: scale(1.5);
                }
            `}</style>
        </div>
    );
}
