export const projects = [
    {
        id: 1,
        slug: 'my-diary',
        titleKo: '나의 일기',
        titleEn: 'My Diary',
        descKo:
            '핵심 학습: Context API + useReducer로 전역 상태를 직접 설계하고 localStorage만으로 영속성을 구현 — 백엔드 없이도 쓸 만한 앱이 나온다는 것을 증명한 React 기초 다지기 프로젝트.',
        descEn:
            'Key takeaway: designed global state from scratch with Context API + useReducer and shipped persistence using only localStorage — proving a useful app can ship without a backend. React fundamentals, hardened.',
        tags: ['React', 'React Router', 'Context API', 'localStorage'],
        link: null,
        github: null,
        color: '#6366f1',
        image: '/projects/p1-diary.png',
        participantsKo: '(1인 개발 - 교육용)',
        participantsEn: '(Personal Use for Education)',
        detailKo: {
            overview: 'React 실전 감각을 기르기 위해 만든 감정 일기 앱. 서버나 DB를 붙이지 않고 localStorage만으로 영속성을 해결하면서, Context API + useReducer 패턴으로 전역 상태를 직접 설계한 것이 이 프로젝트의 핵심입니다. 규모는 작지만 "라이브러리에 의존하지 않고 React의 원리로 끝까지 밀어붙여 본다"는 목적이 뚜렷한 프로젝트였습니다.',
            features: [
                '5가지 감정 이모지 (매우 좋음, 좋음, 보통, 나쁨, 매우 나쁨) 선택',
                '일기 목록 최신순 정렬 및 날짜 필터',
                '일기 작성 / 수정 / 삭제 (CRUD 완전 구현)',
                'localStorage 기반 영구 데이터 저장',
                'React Context API + useReducer 전역 상태 관리',
                'React Router DOM v7 SPA 라우팅',
            ],
            techDetail: 'React 19, React Router DOM 7, useReducer, Context API, localStorage',
        },
        detailEn: {
            overview: 'An emotion diary app built to sharpen my React fundamentals. The heart of the project: solving persistence with only localStorage (no server, no DB) and designing global state by hand with Context API + useReducer — instead of reaching for Redux or Zustand. Small in scope, but deliberate in its goal of pushing React\'s built-in primitives as far as they go.',
            features: [
                '5 emotion emoji options (Very Good, Good, Neutral, Bad, Very Bad)',
                'Diary list sorted by most recent, with date filter',
                'Full CRUD — create, edit, and delete diary entries',
                'Permanent data storage via localStorage',
                'Global state management with React Context API + useReducer',
                'SPA routing with React Router DOM v7',
            ],
            techDetail: 'React 19, React Router DOM 7, useReducer, Context API, localStorage',
        },
    },
    {
        id: 2,
        slug: 'shopping-mall',
        titleKo: '도깨비 쇼핑몰',
        titleEn: 'Goblin Shopping Mall',
        descKo:
            '핵심 경험: 아이디어에서 실제 운영되는 URL까지의 전체 루프를 처음 완주한 팀 프로젝트. 외부 API 연동, 라우트 간 장바구니 상태 유지, Vercel 배포까지 "라이브로 돌아가는 서비스를 만든다"는 감각을 잡은 단계.',
        descEn:
            'Key takeaway: first end-to-end run from idea to a live URL. Worked across a team to integrate a real product API, keep cart state consistent across routes, and ship the whole thing to Vercel — the moment shipping actually felt like shipping.',
        tags: ['React', 'Vercel', 'JavaScript', 'CSS'],
        link: 'https://react-shoppingmall-proj.vercel.app/',
        github: null,
        color: '#f59e0b',
        image: '/projects/shopping-mall.png',
        participantsKo: '전현식 외 3명',
        participantsEn: 'Hyunsik Jeon and 3 others',
        detailKo: {
            overview: '팀 단위로 React 이커머스를 처음부터 끝까지 만들어 실제 배포까지 끌고 간 프로젝트. 단순 기능 구현보다 "외부 API → 프론트 상태 → 라우팅 → 배포"로 이어지는 전체 파이프라인을 직접 감당해 본 것이 큰 수확이었습니다. 18개 이상의 카테고리 필터, 가격 정렬, 키워드 검색 같은 기능보다도, 팀원들과 충돌 없이 함께 만들어 Vercel에서 실제로 돌아가는 서비스를 남겼다는 점에 의미가 있습니다.',
            features: [
                '18개 이상의 상품 카테고리 필터 (전자제품, 뷰티, 패션 등)',
                '가격 낮은 순 / 높은 순 정렬',
                '키워드 검색 실시간 필터링',
                '장바구니 추가 및 수량 관리',
                '상품 상세 페이지 개별 라우팅',
                'Vercel 배포 및 운영',
            ],
            techDetail: 'React, JavaScript, CSS, Vercel, Fake Store API',
        },
        detailEn: {
            overview: 'My first team build of a full e-commerce frontend in React, carried all the way to a deployed URL. What I valued wasn\'t the feature checklist but owning the entire pipeline — external API → frontend state → routing → production deploy — without it breaking between teammates. 18+ category filters, sorting, keyword search, and cart management are the "what"; collaborating without merge chaos and leaving a real, live service on Vercel is the "why it mattered".',
            features: [
                '18+ product category filters (Electronics, Beauty, Fashion, etc.)',
                'Sort by price: Low to High / High to Low',
                'Real-time keyword search filtering',
                'Add to cart and quantity management',
                'Individual product detail pages with routing',
                'Deployed and hosted on Vercel',
            ],
            techDetail: 'React, JavaScript, CSS, Vercel, Fake Store API',
        },
    },
    {
        id: 3,
        slug: 'crazy-arcade',
        titleKo: '크레이지 아케이드 레플리카',
        titleEn: 'Crazy Arcade Replica',
        descKo:
            '핵심 학습: HTTP 요청/응답 모델로는 풀 수 없는 실시간 동시성 문제를 WebSocket으로 직접 설계. 로비 → 대기방 → 게임방으로 이어지는 상태 동기화와 레이스 컨디션을 다뤄보며 "실시간 아키텍처"가 무엇인지 체감.',
        descEn:
            'Key takeaway: learned what "real-time architecture" actually means by designing WebSocket-driven state sync across lobby → waiting room → game room — handling race conditions that plain HTTP can\'t express. A clone on the surface, an architecture lesson underneath.',
        tags: ['React', 'FastAPI', 'WebSocket', 'MySQL', 'Python'],
        link: null,
        github: null,
        color: '#10b981',
        image: '/projects/p3-arcade.png',
        participantsKo: '전현식 외 3명',
        participantsEn: 'Hyunsik Jeon and 3 others',
        detailKo: {
            overview: '크레이지 아케이드 리메이크라는 "재미있는 껍데기" 아래에서 실시간 시스템 설계를 제대로 연습한 프로젝트. REST API만으로는 동기화할 수 없는 플레이어 간 상태 — 폭탄 설치, 폭발 판정, 방 입장/퇴장 — 을 WebSocket으로 어떻게 일관되게 다룰지가 전부였습니다. React 프론트와 FastAPI + MySQL 백엔드를 실시간 채널로 엮어 보며 "실시간"이라는 단어의 무게를 체감한 프로젝트입니다.',
            features: [
                'WebSocket 기반 실시간 게임 상태 동기화',
                '로비 → 대기방 → 게임방 3단계 방 시스템',
                '실시간 채팅 기능 (채팅방 WebSocket)',
                '물폭탄 설치 및 폭발 범위 계산 게임 로직',
                '아이템 (스피드, 폭탄 수, 폭발 반경) 시스템',
                'MySQL + SQLAlchemy 유저 및 방 데이터 관리',
                'FastAPI CORS 처리 및 REST API 엔드포인트',
            ],
            techDetail: 'React 19, FastAPI, Python, WebSocket, MySQL, SQLAlchemy, Axios',
        },
        detailEn: {
            overview: 'A Crazy Arcade remake that was really an excuse to practice real-time system design. The whole project centered on what REST can\'t do — keeping bomb placement, blast resolution, and room join/leave events consistent between players over WebSocket. Wiring a React frontend to a FastAPI + MySQL backend through a live channel is where the word "real-time" stopped being a buzzword for me.',
            features: [
                'Real-time game state sync via WebSocket',
                '3-tier room system: Lobby → Waiting Room → Game Room',
                'Live in-game chat via dedicated chat WebSocket',
                'Water bomb placement and blast radius game logic',
                'Item system: Speed, Bomb Count, Explosion Range power-ups',
                'MySQL + SQLAlchemy for user and room data management',
                'FastAPI CORS handling and REST API endpoints',
            ],
            techDetail: 'React 19, FastAPI, Python, WebSocket, MySQL, SQLAlchemy, Axios',
        },
    },
    {
        id: 4,
        slug: 'vaccine-daily',
        titleKo: '백신일보',
        titleEn: 'Vaccine Daily Report',
        descKo:
            '핵심 성과: "LLM 한 번 호출하면 끝"이라는 접근을 깨뜨린 프로젝트. Writer → Critic → Editor 3단계 에이전트와 HDBSCAN + ko-sroberta 클러스터링으로 토큰 비용은 줄이고 환각은 잡았으며, 그 위에 GraphRAG로 언론사 논조 분석까지.',
        descEn:
            'Key takeaway: proved that "just call an LLM" is not the answer. Engineered a 3-stage agent pipeline (Writer → Critic → Editor) and replaced naive embedding calls with HDBSCAN + ko-sroberta clustering — dropping token cost while cutting hallucinations. GraphRAG sits on top for outlet-bias analysis.',
        tags: ['React', 'FastAPI', 'GraphRAG', 'Agentic Workflow', 'LLM', 'ChromaDB', 'AWS EC2'],
        link: 'https://jeonhs9110.github.io/vaccine-daily/',
        github: 'https://github.com/jeonhs9110/vaccine-daily',
        video: 'https://youtu.be/MtE-sdo6wY0?si=uVqHrozkFxK2__HM',
        color: '#3b82f6',
        image: '/projects/pinned/vaccine-main.png',
        images: [
            '/projects/pinned/vaccine-main.png',
            '/projects/pinned/vaccine-article.png',
        ],
        participantsKo: '전현식 외 2명',
        participantsEn: 'Hyunsik Jeon and 2 others',
        detailKo: {
            overview: '"LLM만 잘 쓰면 해결된다"는 접근의 한계를 제대로 마주한 프로젝트. GPT-4o-mini 하나에 기대는 대신, Writer → Critic → Editor 3단계 에이전트 파이프라인을 설계해 환각을 잡고, HDBSCAN + ko-sroberta로 기사 단위 클러스터링을 돌려 토큰 비용을 체계적으로 줄였습니다. 여기에 GraphRAG로 언론사별 보도 논조까지 분석해, 단순 요약을 넘어 "신뢰할 수 있는 뉴스 리포트"를 자동 생성하는 시스템으로 끌어올렸습니다.',
            features: [
                '[데이터 수집 및 전처리] Selenium 및 BeautifulSoup을 활용하여 10개 언론사 5분 주기 크롤링 및 HDBSCAN + ko-sroberta 기반 토큰 효율적 기사 클러스터링',
                '[AI 에이전트 리포트] Kiwi 형태소 분석과 GPT-4o-mini 기반의 3단계 에이전트 파이프라인(Writer → Critic → Editor)을 통한 환각 방지 및 리포트 작성',
                '[논조 분석 (GraphRAG)] Entity-Relation 트리플 추출 및 지식 그래프 구축을 통한 개별 언론사별 보도 논조 및 경향 분석 시각화',
                '[개인화 지표] 사용자 구독 키워드 및 열람 데이터를 기반으로 한 다기준 추천 스코어링 및 D3 워드클라우드 시각화',
                '[기타] 문장 임베딩 코사인 유사도 인용 검증, 독자 인구통계 대시보드(Recharts) 및 Web Speech API 기반 TTS',
            ],
            techDetail: 'React 18, FastAPI, PostgreSQL 15, ChromaDB, GPT-4o-mini, ko-sroberta, HDBSCAN, Docker Compose, AWS EC2',
        },
        detailEn: {
            overview: 'This project is where I hit the ceiling of "just prompt an LLM better." Instead of leaning on GPT-4o-mini alone, I designed a 3-stage agent pipeline — Writer → Critic → Editor — to catch hallucinations, and layered HDBSCAN + ko-sroberta clustering to cut token cost in a principled way. GraphRAG on top analyzes outlet-level reporting bias, pushing the system past "summarization" into trustworthy news reporting.',
            features: [
                '[Data Pipeline] Selenium & BeautifulSoup scraping of 10 outlets every 5 mins with token-efficient clustering via HDBSCAN + ko-sroberta',
                '[AI Agent Pipeline] 3-stage Agentic Workflow (Writer → Critic → Editor) for hallucination-free reporting and verification',
                '[Tone Analysis (GraphRAG)] Knowledge graph construction via Entity-Relation extraction to visualize media outlet reporting bias',
                '[Personalization] Multi-criteria scoring based on keywords and reading history with D3 Word Cloud visualization',
                '[Personalized Recommendations] Multi-criteria scoring based on subscription keywords/history with D3 Word Clouds',
                '[Other] Cosine similarity citation verification, Recharts demographic dashboards, and Web Speech API TTS',
            ],
            techDetail: 'React 18, FastAPI, PostgreSQL 15, ChromaDB, GPT-4o-mini, ko-sroberta, HDBSCAN, Docker Compose, AWS EC2',
        },
    },
    {
        id: 5,
        slug: 'football-ai',
        titleKo: 'FOBO AI — 유럽 축구 경기 예측',
        titleEn: 'FOBO AI — European Football Prediction',
        descKo:
            '핵심 성과: PyTorch Transformer + Graph Attention Network + Dixon-Coles 보정 + PPO 강화학습 + XGBoost/LightGBM 앙상블을 8단계 파이프라인으로 연결한 엔드투엔드 ML 시스템. 13개 유럽 리그를 대상으로 앙상블 확률 77%+ · 우세팀 필터가 동시에 만족하면 적중률 ~90%, PPO 에이전트가 ≥90% 확신으로 동의하면 ~95%까지 상승. Google Cloud 2-VM 아키텍처로 월 ~$26 운영.',
        descEn:
            'Key takeaway: an end-to-end ML system chaining PyTorch Transformer + Graph Attention Network + Dixon-Coles correction + PPO reinforcement learning + XGBoost/LightGBM ensemble into an 8-stage pipeline. Across 13 European leagues: ~90% hit rate when ensemble top-market confidence ≥77% + favourite filter; rises to ~95% when the PPO agent independently agrees at ≥90%. Deployed on Google Cloud via a 2-VM architecture for ~$26/month.',
        tags: ['PyTorch', 'Transformer', 'Graph Attention Network', 'PPO RL', 'XGBoost', 'LightGBM', 'Flask', 'Google Cloud'],
        link: 'http://34.64.147.124/',
        github: 'https://github.com/jeonhs9110/epl-showcase',
        color: '#ef4444',
        image: '/projects/pinned/epl-home.png',
        images: [
            '/projects/pinned/epl-home.png',
            '/projects/pinned/epl-predict.png',
        ],
        participantsKo: '(1인 개발)',
        participantsEn: 'Hyunsik Jeon (Solo)',
        detailKo: {
            overview: 'FOBO AI(Football Outcome Prediction Optimiser)는 유럽 13개 리그의 경기 결과를 예측하는 프로덕션급 머신러닝 시스템입니다. Flashscore에서 경기 데이터를 병렬 스크래핑한 뒤, Temporal Transformer + Graph Attention Network로 팀 간 상대 강도를 반영한 경기별 기대 골(xG)을 출력하고, Dixon-Coles 보정이 적용된 Poisson 확률 격자에서 승/무/패 · Over 2.5 · BTTS를 해석적으로 유도합니다. 위에 XGBoost + LightGBM 하이브리드 앙상블 + Platt 보정을 얹고, PPO 강화학습 에이전트가 Kelly 기준 보상으로 "언제 예측을 행동으로 옮길지"를 별도 학습합니다. 전체 파이프라인은 스크래핑 → 검증 → 리그별 시퀀스 최적화 → 딥러닝(~770 epoch) → 하이브리드 앙상블 → 보정 → RL 파인튜닝 → Flask API의 8단계로 Google Cloud 2-VM(CPU 상시 + GPU 온디맨드) 위에 배포되어 월 약 $26로 운영됩니다.',
            features: [
                '[스크래핑] Flashscore 13개 리그 병렬 크롤링 — 증분 재실행으로 신규 경기만 가져옴',
                '[딥러닝] PyTorch Transformer + GAT + Dixon-Coles NLL — 약팀이 강팀을 상대하면 "깊게 수비하는" 상대적 태세까지 추론',
                '[강화학습] PPO + GAE, Kelly-Criterion 보상 — 확률이 높아도 시장이 더 높으면 "Pass"를 학습',
                '[앙상블] Transformer 임베딩 위에 XGBoost + LightGBM 하이브리드',
                '[보정] Platt 스케일링으로 보고 확률을 실제 적중률과 정렬',
                '[시스템] Flask API + 다국어 프론트 + GPT-4o-mini 챗봇 (오늘 경기 한정, FOBO 파이프라인 컴포넌트를 근거로 응답)',
                '[배포] Google Cloud asia-northeast3 — 상시 CPU VM + 온디맨드 GPU VM, 매일 11 KST 자동 스크래핑',
                '[결과] 롤링 백테스트 기준 앙상블 ≥77% + 우세팀 필터 적중률 ~90%, PPO ≥90% 동의 시 ~95%',
            ],
            techDetail: 'Python 3.11, PyTorch 2.x, Graph Attention Network, PPO + GAE, XGBoost, LightGBM, scikit-learn (Platt), Dixon-Coles, Flask 3, GCP (Compute Engine 2-VM, asia-northeast3)',
        },
        detailEn: {
            overview: 'FOBO AI (Football Outcome Prediction Optimiser) is a production-grade ML system for predicting match outcomes across 13 European leagues. It parallel-scrapes Flashscore, runs a Temporal Transformer + Graph Attention Network (propagating team strength across a match graph) to produce per-match expected goals (xG), derives W/D/L · Over 2.5 · BTTS analytically from a Dixon-Coles-corrected Poisson grid, and layers an XGBoost + LightGBM hybrid ensemble with Platt calibration on top. A PPO reinforcement-learning agent trained on Kelly-Criterion-shaped reward decides *when* to act on a prediction rather than what the prediction is. Eight stages in total — scrape → validate → per-league sequence optimisation → deep-learning training (~770 epochs) → hybrid ensemble → calibration → RL fine-tune → Flask API — deployed to Google Cloud via a 2-VM architecture (always-on CPU + on-demand GPU) for ~$26/month.',
            features: [
                '[Scraping] Parallel Flashscore ingestion for 13 leagues, incremental re-runs fetch only new matches',
                '[Deep learning] PyTorch Transformer + GAT + Dixon-Coles NLL — the GAT propagates strength across a match graph so the model infers defensive posture when a weak team meets a strong one',
                '[Reinforcement learning] PPO + GAE with Kelly-Criterion reward — the agent learns that high predicted probability ≠ positive EV unless the market underprices it',
                '[Ensemble] Transformer embeddings fed into a hybrid XGBoost + LightGBM tree ensemble',
                '[Calibration] Platt scaling aligns reported probability with empirical hit rate',
                '[System] Flask API + bilingual frontend + GPT-4o-mini chatbot grounded in the FOBO pipeline (scoped to today\'s matches)',
                '[Deployment] Google Cloud asia-northeast3 — always-on CPU VM + on-demand GPU VM, daily 11 KST auto-scrape',
                '[Results] Rolling backtests: ~90% hit rate at ensemble ≥77% + favourite filter; ~95% when the PPO agent independently agrees at ≥90%',
            ],
            techDetail: 'Python 3.11, PyTorch 2.x, Graph Attention Network, PPO + GAE, XGBoost, LightGBM, scikit-learn (Platt), Dixon-Coles, Flask 3, GCP Compute Engine (2-VM, asia-northeast3)',
        },
    },
    {
        id: 6,
        slug: 'kokkok-garden',
        titleKo: 'KOKKOK Garden (K-뷰티 이커머스)',
        titleEn: 'KOKKOK Garden (K-Beauty E-commerce)',
        descKo:
            '핵심 성과: 바이브 코딩으로 프론트→백엔드→DB→챗봇까지 풀스택을 며칠 만에 세움. Next.js + Supabase + GPT-4o mini로 5개 국어 자동 번역과 AI 챗봇까지 얹어, 기획부터 배포까지의 속도를 증명한 멀티리전 K-뷰티 이커머스.',
        descEn:
            'Key takeaway: stood up a full stack — frontend → backend → DB → chatbot — in days using vibe coding. A multi-region K-beauty e-commerce on Next.js + Supabase with GPT-4o mini translating into 5 languages and an AI chatbot, proving idea-to-deployment speed end-to-end.',
        tags: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS', 'OpenAI', 'Vercel'],
        link: 'https://kokv2.vercel.app',
        github: 'https://github.com/jeonhs9110/kok_v2',
        color: '#ec4899',
        image: null,
        participantsKo: '(1인 개발)',
        participantsEn: 'Hyunsik Jeon (Personal Use)',
        detailKo: {
            overview: '바이브 코딩(vibe coding) 방식으로 기획 → UI → API → DB → 챗봇까지 풀스택을 빠르게 밀어붙여 완성한 한국 화장품 멀티리전 이커머스입니다. 한국 사용자는 구매 가능한 `/kr` 스토어로, 해외 사용자는 뷰잉 + AI 챗봇 중심의 `/gl` 스토어로 자동 분기됩니다. 핵심은 "아이디어에서 배포까지의 속도" — Next.js 16 + Supabase + Tailwind 조합으로 프론트/백엔드/DB/인증/스토리지를 최소한의 보일러플레이트로 엮어 냈고, GPT-4o mini를 unstable_cache에 물려 5개국어(영·중·일·베·태) 번역까지 자연스럽게 얹었습니다.',
            features: [
                '[멀티리전 라우팅] `x-user-country` 헤더 기반 KR/GL 자동 분기 및 6개 언어 라우트',
                '[AI 번역] GPT-4o mini로 상품 데이터 5개국어 자동 번역, unstable_cache로 24시간 캐싱',
                '[AI 챗봇] 글로벌 스토어에 K-뷰티 상담 챗봇 탑재로 해외 뷰잉 고객 경험 강화',
                '[백엔드] Supabase(PostgreSQL + Auth + Storage)로 관리자 인증, 상품 CRUD, 이미지 업로드까지 일원화',
                '[관리자] /admin 대시보드에서 상품·Shorts·미디어 관리, 쿠키 기반 세션 인증',
                '[배포] Vercel 배포 + https://kokv2.vercel.app 운영',
            ],
            techDetail: 'Next.js 16 (App Router), React 19, TypeScript 5, Tailwind CSS 4, Supabase, OpenAI GPT-4o mini, Embla Carousel, Vercel',
        },
        detailEn: {
            overview: 'A multi-region K-beauty e-commerce prototype built in "vibe coding" mode — pushing frontend, backend, DB, and an AI chatbot to production in days instead of weeks. Korean users are routed to a purchasable `/kr` store; international users land on a viewing-only `/gl` store centered on an AI chatbot. The real point of this project was speed from idea to deploy: Next.js 16 + Supabase + Tailwind handled front/back/DB/auth/storage with minimal boilerplate, and GPT-4o mini behind `unstable_cache` layered on 5-language translation (EN/CN/JP/VN/TH) almost for free.',
            features: [
                '[Multi-region routing] Auto split between KR and GL stores via `x-user-country`, with six language routes',
                '[AI translation] GPT-4o mini translates product data into 5 languages, cached for 24h via `unstable_cache`',
                '[AI chatbot] K-beauty consultation chatbot embedded in the GL store to augment viewing-only UX',
                '[Backend] Supabase (PostgreSQL + Auth + Storage) unifies admin auth, product CRUD, and image upload',
                '[Admin] `/admin` dashboard for products, Shorts, and media with cookie-based session auth',
                '[Deploy] Live on Vercel at https://kokv2.vercel.app',
            ],
            techDetail: 'Next.js 16 (App Router), React 19, TypeScript 5, Tailwind CSS 4, Supabase, OpenAI GPT-4o mini, Embla Carousel, Vercel',
        },
    },
    {
        id: 7,
        slug: 'aiim',
        titleKo: 'AIIM — AI 인플루언서 매칭',
        titleEn: 'AIIM — AI Influencer Match',
        descKo:
            '핵심 성과: YouTube + Instagram + TikTok에서 14개 언어권 5,300명+ 크리에이터를 수집하고 LLM 기반으로 브랜드 적합도를 매칭하는 엔드투엔드 플랫폼. 세 가지 수집 파이프라인(할당량 10K/day YouTube API · 200 calls/hr Meta Graph API · 2대 병렬 Selenium 워커)을 LLM 데이터 보강 층과 통합해 Google Cloud에서 24/7 운영. 다국어 해시태그 전략으로 30분 실행에 YouTube 신규 400명, IG 비즈니스 이메일 323건 자동 추출.',
        descEn:
            'Key takeaway: an end-to-end platform that ingests 5,300+ creators across YouTube + Instagram + TikTok in 14 languages and ranks brand-fit via LLM reasoning. Three very different ingestion pipelines (quota-bound YouTube Data API, rate-limited Meta Graph API, and two parallel human-shaped Selenium workers) are unified with an LLM enrichment layer and served 24/7 on Google Cloud. Multilingual hashtag discovery surfaced 400 new YouTube creators in a single 30-minute run and extracted 323 IG business emails.',
        tags: ['Python', 'FastAPI', 'Next.js 14', 'Cloud Run', 'Cloud SQL (Postgres)', 'Selenium', 'Meta Graph API', 'YouTube Data API', 'LLM'],
        link: 'https://aiim-frontend-559416574965.asia-northeast3.run.app/',
        github: 'https://github.com/jeonhs9110/AIIM-Showcase',
        color: '#8b5cf6',
        image: '/projects/pinned/aiim-browse.png',
        images: [
            '/projects/pinned/aiim-browse.png',
            '/projects/pinned/aiim-recommend.png',
            '/projects/pinned/aiim-influencer.png',
        ],
        participantsKo: '(1인 개발)',
        participantsEn: 'Hyunsik Jeon (Solo)',
        detailKo: {
            overview: 'AIIM(AI Influencer Match)은 브랜드 마케팅 팀이 수많은 소셜 미디어 크리에이터 중 캠페인에 가장 적합한 인플루언서를 찾을 수 있도록 설계한 엔드투엔드 클라우드 플랫폼입니다. YouTube Data API v3, Meta Graph API, 자체 Selenium IG 스크래퍼 세 가지 수집 경로를 병렬로 운영하며 **14개 언어권에서 5,300명 이상의 크리에이터**를 지속적으로 수집합니다. 각 프로필은 LLM 파이프라인이 국가·언어·브랜드 협업 이력·콘텐츠 카테고리(뷰티·패션·푸드·라이프스타일 등)로 자동 정제합니다. 전체 시스템은 Google Cloud(Cloud Run + Cloud SQL + Secret Manager + Artifact Registry)에 배포되어 24/7 서비스되며, `probe-before-bulk` 원칙과 실시간 비용 추적으로 유료 API 운영비를 예측 가능한 범위에서 관리합니다.',
            features: [
                '[멀티 플랫폼 수집] YouTube (1,584) · Instagram (3,735) · TikTok (16) — 총 5,300명+ 크리에이터, 한국 + 글로벌 시장',
                '[다국어 해시태그 전략] 영어 쿼리가 수렴하는 한계를 넘어 14개 문자 체계(광고·スポンサー·رعاية 등)로 검색 — 30분 실행으로 신규 400명 확보',
                '[LLM 데이터 보강] 각 프로필의 국가·언어·브랜드 협업·콘텐츠 카테고리·연락처 자동 추출 · 프롬프트 캐싱으로 단가 관리',
                '[추천 엔진] 제품/타겟/예산을 자연어로 입력 → 근거 포함 랭킹 반환. 데모 모드 게이팅으로 공개 URL에서 유료 API 소진 방지',
                '[비용 규율] `probe-one-before-bulk` 원칙 + 실시간 비용 트래킹 — 스크래퍼 벤더 예산 사고 후 도입',
                '[휴먼-셰이프드 Selenium] μs 단위 드웰 랜덤화, 마우스 wander, 5–15분 AFK 스케줄러 — 수개월 연속 운영에도 challenge wall 없음',
                '[장애 복구] Meta/YouTube 쿼터 초과 시 row-level 커밋 + 재개 가능한 요약 로그',
                '[배포] GCP asia-northeast3 — Cloud Run (백엔드 + 프론트) + Cloud SQL Postgres + Cloud Build CI',
            ],
            techDetail: 'Python 3.10, FastAPI, SQLAlchemy, Alembic, Next.js 14 (App Router), TypeScript, Tailwind CSS, shadcn/ui, PostgreSQL (Cloud SQL), YouTube Data API v3, Meta Graph API, Selenium, GCP (Cloud Run, Artifact Registry, Cloud Build, Secret Manager)',
        },
        detailEn: {
            overview: 'AIIM (AI Influencer Match) is an end-to-end cloud platform that helps brand marketing teams find the right creator among a crowded social-media landscape. Three very different ingestion pipelines run in parallel — YouTube Data API v3, Meta Graph API, and a purpose-built Selenium IG scraper — feeding **5,300+ creators across 14 languages** into one unified schema. An LLM enrichment layer then structures each profile into searchable fields: primary language, audience country mix, vertical (beauty / fashion / food / lifestyle / tech), brand-deal history, monetisation intent. The whole system runs 24/7 on Google Cloud (Cloud Run + Cloud SQL + Secret Manager + Artifact Registry), with a `probe-before-bulk` discipline and real-time per-call cost tracking that keeps paid-API spend inside a predictable envelope.',
            features: [
                '[Multi-platform ingestion] YouTube (1,584) · Instagram (3,735) · TikTok (16) — 5,300+ creators across Korean + global markets',
                '[Multilingual hashtag discovery] Search native-language monetisation tags (광고 · スポンサー · رعاية · publicidade · iklan …) to escape the English-query convergence trap — surfaced 400 new YouTube creators in one 30-minute run',
                '[LLM enrichment] Structures bio, captions, and brand mentions into searchable fields (country, language, vertical, brand history, contact) with prompt caching for unit-economics sanity',
                '[Recommendation engine] Describe product + target + budget in plain English → ranked shortlist with per-pick reasoning. Demo-mode gating blocks paid-API burn on the public URL, one env flag away',
                '[Cost discipline] `probe-one-before-bulk` rule for every paid API after a scraper-vendor budget blow-up — single most useful post-mortem in the project',
                '[Human-shaped Selenium] μs-precision dwell randomisation, mouse wander, 5–15 min AFK scheduler — runs for months without a single challenge wall',
                '[Graceful degradation] Per-row commits + resume logs when Meta / YouTube quotas hit ceiling mid-run, so multi-hour scrapes never lose work',
                '[Deployment] GCP asia-northeast3 — Cloud Run (backend + frontend) + Cloud SQL Postgres + Cloud Build CI',
            ],
            techDetail: 'Python 3.10, FastAPI, SQLAlchemy, Alembic, Next.js 14 (App Router), TypeScript, Tailwind CSS, shadcn/ui, PostgreSQL (Cloud SQL), YouTube Data API v3, Meta Graph API, Selenium, GCP (Cloud Run, Artifact Registry, Cloud Build, Secret Manager)',
        },
    },
    {
        id: 8,
        slug: 'iamx6',
        titleKo: 'IAMX6 — 네이버 블로그 자동화 데스크톱 앱',
        titleEn: 'IAMX6 — Naver Blog Automation Desktop App',
        descKo:
            '핵심 성과: 단일 ~67MB portable .exe로 배포되는 Electron 데스크톱 앱. Puppeteer가 사용자의 실제 Chrome을 제어해 서로이웃 신청 · 댓글/좋아요 · 방문당 답글을 자동화하고, LLM이 포스팅 제목·본문을 읽어 문맥에 맞는 한국어 댓글을 실시간 생성. 3중 코드 보호(제어 흐름 평탄화 + V8 바이트코드 + Electron Fuses)로 소스 추출을 사실상 차단.',
        descEn:
            'Key takeaway: a single ~67MB portable .exe desktop app built on Electron. Puppeteer drives the user\'s real Chrome to automate neighbor requests, comment/like workflows, and visitor replies while an LLM reads post title + body to generate Korean comments in context. Three-layer hardening — control-flow-flattened JS + V8 bytecode + Electron Fuses — makes source extraction impractical.',
        tags: ['Electron', 'Puppeteer', 'Node.js', 'LLM', 'Bytenode (V8)', 'Electron Fuses', 'Windows portable .exe'],
        link: null,
        github: 'https://github.com/jeonhs9110/IAMX6-showcase',
        color: '#14b8a6',
        image: null,
        participantsKo: '(1인 개발 — 소스 비공개)',
        participantsEn: 'Hyunsik Jeon (Solo — source private)',
        detailKo: {
            overview: 'IAMX6는 네이버 블로그 운영자를 위한 올인원 자동화 데스크톱 애플리케이션입니다. Electron GUI 위에 Puppeteer로 실제 Chrome을 제어하여 **서로이웃 신청 / 댓글·좋아요 / 방문당 답글** 세 가지 워크플로를 사람처럼 자연스럽게 수행합니다. 댓글은 LLM이 포스팅 제목과 본문을 읽고 문맥에 맞춰 실시간 생성 — 단순 템플릿이 아닌 실제 독자 같은 한국어 1~2문장 댓글을 만듭니다. 행동 시뮬레이션은 디테일에 집중했습니다. 스크롤은 가우시안 가속·감속, 드웰 시간은 본문 글자 수에 비례하며 ±25% + 밀리초 노이즈로 절대 같은 시간이 두 번 나오지 않고, 35% 확률로 "다른 곳을 잠깐 본다" 동작까지 삽입합니다. 코드 보호는 3중 — 제어 흐름 평탄화 + base64 문자열 배열 + self-defending 처리 + 핵심 로직 V8 바이트코드 컴파일 + Electron Fuses로 `ELECTRON_RUN_AS_NODE`, `--inspect`, `NODE_OPTIONS` 런타임 봉쇄, 거기에 KST 날짜 게이트까지 적용되어 있습니다.',
            features: [
                '[3-워크플로 통합] 서로이웃 신청 · 댓글/좋아요 · 방문당 답글을 4탭 GUI에서 일원화',
                '[Puppeteer 자동화] 실제 네이버 세션을 사용자가 직접 로그인(2FA/CAPTCHA) 후, 봇이 이어받아 실행',
                '[LLM 댓글 생성] 포스팅 제목+본문 → 맥락 맞춤 한국어 코멘트 · 회당 6–10개 캐시 한도로 단가 관리',
                '[휴먼 시뮬레이션] 글자수 비례 드웰 + ±25% 지터 + ms 노이즈 + 35% "한눈팔기" 액션',
                '[3중 코드 보호] javascript-obfuscator → bytenode(.jsc) → Electron Fuses — `npx asar extract` + 디버거 어태치 + `run-as-Node` 트릭 모두 차단',
                '[날짜 게이트] KST 기준 라이선스 만료일 체크 후 다이얼로그 → 즉시 종료',
                '[4계절 테마] ❄️ Winter / ☀️ Summer / 🌸 Spring / 🍂 Autumn — 캔버스 기반 파티클 엔진, 선택값 localStorage 저장',
                '[배포] 단일 파일 portable .exe (~67MB, v1.21) · 인스톨러 불필요 · 콘솔 창 없음',
            ],
            techDetail: 'Electron 25.9 (Chromium + Node 18), Puppeteer-core 24, OpenAI GPT-4o-mini, javascript-obfuscator, bytenode (V8 bytecode), @electron/fuses, electron-builder (Windows portable)',
        },
        detailEn: {
            overview: 'IAMX6 is an all-in-one automation desktop app for Naver Blog owners. On top of an Electron GUI, Puppeteer drives a real Chrome window to perform three workflows — **neighbor requests, comment/like automation, and visitor auto-reply** — with human-shaped timing. Comments are generated by an LLM reading the post\'s title + body in real time, not a template, producing 1-2 sentence Korean replies that read like an actual reader. Behavior simulation is intentionally detailed: Gaussian-accelerated scroll, dwell proportional to content length with ±25% jitter + millisecond noise so no two dwells repeat, and a 35% "glance away" distraction pattern. Code hardening is three-layered: control-flow-flattened + base64 string arrays + self-defending JS obfuscation → V8 bytecode compile of the core `automator.js` so the source never ships → Electron Fuses that shut down `ELECTRON_RUN_AS_NODE`, `--inspect`, and `NODE_OPTIONS` extraction routes at runtime. A KST-anchored date gate runs before any window is created.',
            features: [
                '[Unified 3-workflow GUI] Neighbor requests · comment/like · visitor auto-reply across a 4-tab GUI',
                '[Puppeteer automation] Real Naver session — user clears 2FA/CAPTCHA manually, bot takes over',
                '[LLM comment generation] Post title + body → context-aware Korean comments · 6–10 fresh-call cap per run for cost control',
                '[Human-shaped behavior] Content-length-proportional dwell + ±25% jitter + ms noise + 35% distraction actions',
                '[3-layer hardening] javascript-obfuscator → bytenode (.jsc) → Electron Fuses — defeats `npx asar extract`, debugger attach, and the "run-as-Node" extraction tricks',
                '[Date gate] KST-aware license expiry check at boot, with native dialog → immediate quit',
                '[4 seasonal themes] ❄️ Winter / ☀️ Summer / 🌸 Spring / 🍂 Autumn — canvas particle engine, selection persisted in localStorage',
                '[Distribution] Single-file portable .exe (~67 MB, v1.21) · no installer · no console window',
            ],
            techDetail: 'Electron 25.9 (Chromium + Node 18), Puppeteer-core 24, OpenAI GPT-4o-mini, javascript-obfuscator, bytenode (V8 bytecode), @electron/fuses, electron-builder (Windows portable)',
        },
    },
];
