export const projects = [
    {
        id: 1,
        slug: 'my-diary',
        titleKo: '나의 일기',
        titleEn: 'My Diary',
        descKo:
            'React로 만든 감정 일기 앱입니다. localStorage를 활용해 브라우저에 일기를 저장하며, 감정 이모지 선택, 날짜별 조회, CRUD 기능을 구현했습니다. Context API와 useReducer를 사용해 전역 상태를 관리합니다.',
        descEn:
            'An emotion-tracking diary app built with React. Diaries are stored locally via localStorage. Features include emotion emoji selection, date-based browsing, and full CRUD. Global state is managed with Context API and useReducer.',
        tags: ['React', 'React Router', 'Context API', 'localStorage'],
        link: null,
        github: null,
        color: '#6366f1',
        image: '/projects/p1-diary.png',
        participantsKo: '(1인 개발 - 교육용)',
        participantsEn: '(Personal Use for Education)',
        detailKo: {
            overview: '나의 일기는 사용자가 매일의 감정을 기록하고 돌아볼 수 있는 웹 일기장입니다. 별도의 서버나 데이터베이스 없이 브라우저의 localStorage만으로 데이터를 영구 저장하는 프론트엔드 중심 프로젝트입니다.',
            features: [
                '5가지 감정 이모지 (매우 좋음, 좋음, 보통, 나쁨, 매우 나쁨) 선택',
                '일기 목록 최신순 정렬 및 날짜 필터',
                '일기 작성 / 수정 / 삭제 (CRUD 완전 구현)',
                'localStorage 기반 영구 데이터 저장',
                'React Context API + useReducer 전역 상태 관리',
                'React Router DOM v7 SPA 라우팅',
            ],
            techDetail: 'React 19, React Router DOM 7, useReducer, Context API, localStorage',
        },
        detailEn: {
            overview: 'My Diary is a web-based diary where users can log and review their daily emotions. It is a frontend-focused project that permanently stores data using only the browser\'s localStorage — no server or database required.',
            features: [
                '5 emotion emoji options (Very Good, Good, Neutral, Bad, Very Bad)',
                'Diary list sorted by most recent, with date filter',
                'Full CRUD — create, edit, and delete diary entries',
                'Permanent data storage via localStorage',
                'Global state management with React Context API + useReducer',
                'SPA routing with React Router DOM v7',
            ],
            techDetail: 'React 19, React Router DOM 7, useReducer, Context API, localStorage',
        },
    },
    {
        id: 2,
        slug: 'shopping-mall',
        titleKo: '도깨비 쇼핑몰',
        titleEn: 'Goblin Shopping Mall',
        descKo:
            'React로 구축한 이커머스 쇼핑몰입니다. 18개 이상의 카테고리 필터, 가격 정렬, 장바구니, 키워드 검색 기능을 구현했으며 Vercel에 배포되어 있습니다.',
        descEn:
            'An e-commerce shopping mall built with React. Features 18+ category filters, price sorting, a shopping cart, and keyword search. Deployed on Vercel.',
        tags: ['React', 'Vercel', 'JavaScript', 'CSS'],
        link: 'https://react-shoppingmall-proj.vercel.app/',
        github: null,
        color: '#f59e0b',
        image: '/projects/shopping-mall.png',
        participantsKo: '전현식 외 3명',
        participantsEn: 'Hyunsik Jeon and 3 others',
        detailKo: {
            overview: '도깨비 쇼핑몰은 React로 제작된 풀 기능 이커머스 프론트엔드 애플리케이션입니다. 실제 상품 데이터 API를 연동하여 현실적인 쇼핑 경험을 제공하며 Vercel을 통해 배포되어 있습니다.',
            features: [
                '18개 이상의 상품 카테고리 필터 (전자제품, 뷰티, 패션 등)',
                '가격 낮은 순 / 높은 순 정렬',
                '키워드 검색 실시간 필터링',
                '장바구니 추가 및 수량 관리',
                '상품 상세 페이지 개별 라우팅',
                'Vercel 배포 및 운영',
            ],
            techDetail: 'React, JavaScript, CSS, Vercel, Fake Store API',
        },
        detailEn: {
            overview: 'Goblin Shopping Mall is a fully-featured e-commerce frontend application built with React. It integrates a real product data API to provide a realistic shopping experience and is deployed on Vercel.',
            features: [
                '18+ product category filters (Electronics, Beauty, Fashion, etc.)',
                'Sort by price: Low to High / High to Low',
                'Real-time keyword search filtering',
                'Add to cart and quantity management',
                'Individual product detail pages with routing',
                'Deployed and hosted on Vercel',
            ],
            techDetail: 'React, JavaScript, CSS, Vercel, Fake Store API',
        },
    },
    {
        id: 3,
        slug: 'crazy-arcade',
        titleKo: '크레이지 아케이드 레플리카',
        titleEn: 'Crazy Arcade Replica',
        descKo:
            'React와 FastAPI로 제작한 실시간 멀티플레이어 게임입니다. WebSocket을 통해 실시간 게임 상태를 동기화하고 로비/대기방/게임방 시스템을 구현했습니다. MySQL로 유저 데이터를 관리합니다.',
        descEn:
            'A real-time multiplayer game built with React and FastAPI. Game state is synchronized in real-time via WebSocket, with lobby, waiting room, and game room systems. User data is managed with MySQL.',
        tags: ['React', 'FastAPI', 'WebSocket', 'MySQL', 'Python'],
        link: null,
        github: null,
        color: '#10b981',
        image: '/projects/p3-arcade.png',
        participantsKo: '전현식 외 3명',
        participantsEn: 'Hyunsik Jeon and 3 others',
        detailKo: {
            overview: '한국의 인기 게임 크레이지 아케이드를 웹 기술로 재현한 실시간 멀티플레이어 게임입니다. React 프론트엔드와 Python FastAPI 백엔드가 WebSocket으로 연결되어 여러 플레이어가 동시에 게임을 즐길 수 있습니다.',
            features: [
                'WebSocket 기반 실시간 게임 상태 동기화',
                '로비 → 대기방 → 게임방 3단계 방 시스템',
                '실시간 채팅 기능 (채팅방 WebSocket)',
                '물폭탄 설치 및 폭발 범위 계산 게임 로직',
                '아이템 (스피드, 폭탄 수, 폭발 반경) 시스템',
                'MySQL + SQLAlchemy 유저 및 방 데이터 관리',
                'FastAPI CORS 처리 및 REST API 엔드포인트',
            ],
            techDetail: 'React 19, FastAPI, Python, WebSocket, MySQL, SQLAlchemy, Axios',
        },
        detailEn: {
            overview: 'A web-based replica of the popular Korean game Crazy Arcade, built with real-time multiplayer technology. A React frontend connects to a Python FastAPI backend via WebSocket, allowing multiple players to play simultaneously.',
            features: [
                'Real-time game state sync via WebSocket',
                '3-tier room system: Lobby → Waiting Room → Game Room',
                'Live in-game chat via dedicated chat WebSocket',
                'Water bomb placement and blast radius game logic',
                'Item system: Speed, Bomb Count, Explosion Range power-ups',
                'MySQL + SQLAlchemy for user and room data management',
                'FastAPI CORS handling and REST API endpoints',
            ],
            techDetail: 'React 19, FastAPI, Python, WebSocket, MySQL, SQLAlchemy, Axios',
        },
    },
    {
        id: 4,
        slug: 'vaccine-daily',
        titleKo: '백신일보',
        titleEn: 'Vaccine Daily Report',
        descKo:
            '단순 LLM 만 사용한 것이 아닌 여러 패키지 및 모델을 검토하여 토큰 효율성과 Multi Agent 기능 구현. 10개 주요 언론사를 실시간 추적하고 검증된 뉴스 리포트를 자동 생성합니다.',
        descEn:
            'Implemented an efficient Multi-Agent system for personalized news reports by optimizing token usage and integrating various ML packages beyond a single LLM.',
        tags: ['React', 'FastAPI', 'GraphRAG', 'Agentic Workflow', 'LLM', 'AWS'],
        link: null,
        github: null,
        video: 'https://youtu.be/MtE-sdo6wY0?si=uVqHrozkFxK2__HM',
        color: '#3b82f6',
        image: '/projects/vaccine-daily.png',
        participantsKo: '전현식 외 2명',
        participantsEn: 'Hyunsik Jeon and 2 others',
        detailKo: {
            overview: '단순 LLM 만 사용한 것이 아닌 여러 패키지 및 모델을 검토하여 토큰 효율성과 Multi Agent 기능 구현을 핵심으로 개발한 뉴스 자동 요약 파이프라인입니다.',
            features: [
                '[데이터 수집 및 전처리] Selenium 및 BeautifulSoup을 활용하여 10개 언론사 5분 주기 크롤링 및 HDBSCAN + ko-sroberta 기반 토큰 효율적 기사 클러스터링',
                '[AI 에이전트 리포트] Kiwi 형태소 분석과 GPT-4o-mini 기반의 3단계 에이전트 파이프라인(Writer → Critic → Editor)을 통한 환각 방지 및 리포트 작성',
                '[논조 분석 (GraphRAG)] Entity-Relation 트리플 추출 및 지식 그래프 구축을 통한 개별 언론사별 보도 논조 및 경향 분석 시각화',
                '[개인화 지표] 사용자 구독 키워드 및 열람 데이터를 기반으로 한 다기준 추천 스코어링 및 D3 워드클라우드 시각화',
                '[기타] 문장 임베딩 코사인 유사도 인용 검증, 독자 인구통계 대시보드(Recharts) 및 Web Speech API 기반 TTS',
            ],
            techDetail: 'React 18, FastAPI, PostgreSQL 15, ChromaDB, GPT-4o-mini, ko-sroberta, HDBSCAN, Docker Compose, AWS EC2',
        },
        detailEn: {
            overview: 'Developed a news summarization pipeline focusing on token efficiency and Multi-Agent functionality by reviewing various packages and models, not just a single LLM.',
            features: [
                '[Data Pipeline] Selenium & BeautifulSoup scraping of 10 outlets every 5 mins with token-efficient clustering via HDBSCAN + ko-sroberta',
                '[AI Agent Pipeline] 3-stage Agentic Workflow (Writer → Critic → Editor) for hallucination-free reporting and verification',
                '[Tone Analysis (GraphRAG)] Knowledge graph construction via Entity-Relation extraction to visualize media outlet reporting bias',
                '[Personalization] Multi-criteria scoring based on keywords and reading history with D3 Word Cloud visualization',
                '[Personalized Recommendations] Multi-criteria scoring based on subscription keywords/history with D3 Word Clouds',
                '[Other] Cosine similarity citation verification, Recharts demographic dashboards, and Web Speech API TTS',
            ],
            techDetail: 'React 18, FastAPI, PostgreSQL 15, ChromaDB, GPT-4o-mini, ko-sroberta, HDBSCAN, Docker Compose, AWS EC2',
        },
    },
    {
        id: 5,
        slug: 'football-ai',
        titleKo: '축구 AI 예측 시스템',
        titleEn: 'Football AI Prediction',
        descKo:
            'Selenium과 BeautifulSoup을 이용한 실시간 데이터 파이프라인을 구축하고, 딥러닝 앙상블 및 강화학습(RL)을 통해 경기 예측 신뢰도를 극대화합니다.',
        descEn:
            'Features a real-time data pipeline built with Selenium/BS4, optimizing match forecasting reliability through deep learning ensembles and Reinforcement Learning.',
        tags: ['Python', 'TensorFlow', 'Reinforcement Learning', 'Monte Carlo', 'FastAPI', 'AI/ML'],
        link: null,
        github: null,
        color: '#ef4444',
        image: '/projects/training-day.png',
        images: [
            '/projects/sports-v7.png',
            '/projects/sports-v6.png',
            '/projects/sports-v5.png',
            '/projects/sports-v4.png',
            '/projects/sports-v3.png',
        ],
        participantsKo: '(1인 개발)',
        participantsEn: 'Hyunsik Jeon (Personal Use)',
        detailKo: {
            overview: 'Selenium과 BeautifulSoup을 이용한 실시간 데이터 파이프라인을 구축하고, 딥러닝 앙상블 및 강화학습(RL)을 통해 예측 신뢰도를 극대화합니다.',
            features: [
                '[Step 1] 데이터 수집: Selenium/BS4 기반 실시간 매치 정보 및 글로벌 배당률 크롤링',
                '[Step 2] 모델 앙상블: TensorFlow DL + XGBoost + LightGBM 트리플 앙상블 아키텍처',
                '[Step 3] 신뢰도 최적화: 강화학습(RL) 에이전트를 통한 모델별 예측 신뢰도 임계값 자동 튜닝',
                '[Step 4] 확률적 추론: 몬테카를로 시뮬레이션 기반의 칼리브레이션 및 결과 확률 산출',
                '[Step 5] 동적 튜닝: 리그별 데이터 휘발성을 반영한 가변 시퀀스 길이 최적화',
                '[Step 6] 전력 분석: ELO 기반 팀 전력 지표 산출 및 GNN 기반 도미넌스 랭킹 적용',
            ],
            techDetail: 'Python, TensorFlow, Reinforcement Learning, Monte Carlo, XGBoost, LightGBM, FastAPI, Pandas',
        },
        detailEn: {
            overview: 'It features a real-time data pipeline built with Selenium and BeautifulSoup, optimizing forecasting reliability through deep learning ensembles and Reinforcement Learning.',
            features: [
                '[Step 1] Data Scrapping: Automated pipeline for match data and global bookmaker odds collection',
                '[Step 2] Predictive Ensembling: Triple architecture — TensorFlow DL + XGBoost + LightGBM',
                '[Step 3] Confidence Optimization: Reinforcement Learning (RL) agent for tuning logical confidence thresholds',
                '[Step 4] Probabilistic Reasoning: Monte Carlo simulation for calibrated outcome probabilities',
                '[Step 5] Dynamic Tuning: Adaptive sequence length optimization based on league-specific volatility',
                '[Step 6] Power Ranking: ELO-based strength metrics and GNN-based dominance analysis',
            ],
            techDetail: 'Python, TensorFlow, Reinforcement Learning, Monte Carlo, XGBoost, LightGBM, FastAPI, Pandas',
        },
    },
];
