export const projects = [
    {
        id: 1,
        slug: 'my-diary',
        titleKo: '나의 일기',
        titleEn: 'My Diary',
        descKo:
            '핵심 학습: Context API + useReducer로 전역 상태를 직접 설계하고 localStorage만으로 영속성을 구현 — 백엔드 없이도 쓸 만한 앱이 나온다는 것을 증명한 React 기초 다지기 프로젝트.',
        descEn:
            'Key takeaway: designed global state from scratch with Context API + useReducer and shipped persistence using only localStorage — proving a useful app can ship without a backend. React fundamentals, hardened.',
        tags: ['React', 'React Router', 'Context API', 'localStorage'],
        link: null,
        github: null,
        color: '#6366f1',
        image: '/projects/p1-diary.png',
        participantsKo: '(1인 개발 - 교육용)',
        participantsEn: '(Personal Use for Education)',
        detailKo: {
            overview: 'React 실전 감각을 기르기 위해 만든 감정 일기 앱. 서버나 DB를 붙이지 않고 localStorage만으로 영속성을 해결하면서, Context API + useReducer 패턴으로 전역 상태를 직접 설계한 것이 이 프로젝트의 핵심입니다. 규모는 작지만 "라이브러리에 의존하지 않고 React의 원리로 끝까지 밀어붙여 본다"는 목적이 뚜렷한 프로젝트였습니다.',
            features: [
                '5가지 감정 이모지 (매우 좋음, 좋음, 보통, 나쁨, 매우 나쁨) 선택',
                '일기 목록 최신순 정렬 및 날짜 필터',
                '일기 작성 / 수정 / 삭제 (CRUD 완전 구현)',
                'localStorage 기반 영구 데이터 저장',
                'React Context API + useReducer 전역 상태 관리',
                'React Router DOM v7 SPA 라우팅',
            ],
            techDetail: 'React 19, React Router DOM 7, useReducer, Context API, localStorage',
        },
        detailEn: {
            overview: 'An emotion diary app built to sharpen my React fundamentals. The heart of the project: solving persistence with only localStorage (no server, no DB) and designing global state by hand with Context API + useReducer — instead of reaching for Redux or Zustand. Small in scope, but deliberate in its goal of pushing React\'s built-in primitives as far as they go.',
            features: [
                '5 emotion emoji options (Very Good, Good, Neutral, Bad, Very Bad)',
                'Diary list sorted by most recent, with date filter',
                'Full CRUD — create, edit, and delete diary entries',
                'Permanent data storage via localStorage',
                'Global state management with React Context API + useReducer',
                'SPA routing with React Router DOM v7',
            ],
            techDetail: 'React 19, React Router DOM 7, useReducer, Context API, localStorage',
        },
    },
    {
        id: 2,
        slug: 'shopping-mall',
        titleKo: '도깨비 쇼핑몰',
        titleEn: 'Goblin Shopping Mall',
        descKo:
            '핵심 경험: 아이디어에서 실제 운영되는 URL까지의 전체 루프를 처음 완주한 팀 프로젝트. 외부 API 연동, 라우트 간 장바구니 상태 유지, Vercel 배포까지 "라이브로 돌아가는 서비스를 만든다"는 감각을 잡은 단계.',
        descEn:
            'Key takeaway: first end-to-end run from idea to a live URL. Worked across a team to integrate a real product API, keep cart state consistent across routes, and ship the whole thing to Vercel — the moment shipping actually felt like shipping.',
        tags: ['React', 'Vercel', 'JavaScript', 'CSS'],
        link: 'https://react-shoppingmall-proj.vercel.app/',
        github: null,
        color: '#f59e0b',
        image: '/projects/shopping-mall.png',
        participantsKo: '전현식 외 3명',
        participantsEn: 'Hyunsik Jeon and 3 others',
        detailKo: {
            overview: '팀 단위로 React 이커머스를 처음부터 끝까지 만들어 실제 배포까지 끌고 간 프로젝트. 단순 기능 구현보다 "외부 API → 프론트 상태 → 라우팅 → 배포"로 이어지는 전체 파이프라인을 직접 감당해 본 것이 큰 수확이었습니다. 18개 이상의 카테고리 필터, 가격 정렬, 키워드 검색 같은 기능보다도, 팀원들과 충돌 없이 함께 만들어 Vercel에서 실제로 돌아가는 서비스를 남겼다는 점에 의미가 있습니다.',
            features: [
                '18개 이상의 상품 카테고리 필터 (전자제품, 뷰티, 패션 등)',
                '가격 낮은 순 / 높은 순 정렬',
                '키워드 검색 실시간 필터링',
                '장바구니 추가 및 수량 관리',
                '상품 상세 페이지 개별 라우팅',
                'Vercel 배포 및 운영',
            ],
            techDetail: 'React, JavaScript, CSS, Vercel, Fake Store API',
        },
        detailEn: {
            overview: 'My first team build of a full e-commerce frontend in React, carried all the way to a deployed URL. What I valued wasn\'t the feature checklist but owning the entire pipeline — external API → frontend state → routing → production deploy — without it breaking between teammates. 18+ category filters, sorting, keyword search, and cart management are the "what"; collaborating without merge chaos and leaving a real, live service on Vercel is the "why it mattered".',
            features: [
                '18+ product category filters (Electronics, Beauty, Fashion, etc.)',
                'Sort by price: Low to High / High to Low',
                'Real-time keyword search filtering',
                'Add to cart and quantity management',
                'Individual product detail pages with routing',
                'Deployed and hosted on Vercel',
            ],
            techDetail: 'React, JavaScript, CSS, Vercel, Fake Store API',
        },
    },
    {
        id: 3,
        slug: 'crazy-arcade',
        titleKo: '크레이지 아케이드 레플리카',
        titleEn: 'Crazy Arcade Replica',
        descKo:
            '핵심 학습: HTTP 요청/응답 모델로는 풀 수 없는 실시간 동시성 문제를 WebSocket으로 직접 설계. 로비 → 대기방 → 게임방으로 이어지는 상태 동기화와 레이스 컨디션을 다뤄보며 "실시간 아키텍처"가 무엇인지 체감.',
        descEn:
            'Key takeaway: learned what "real-time architecture" actually means by designing WebSocket-driven state sync across lobby → waiting room → game room — handling race conditions that plain HTTP can\'t express. A clone on the surface, an architecture lesson underneath.',
        tags: ['React', 'FastAPI', 'WebSocket', 'MySQL', 'Python'],
        link: null,
        github: null,
        color: '#10b981',
        image: '/projects/p3-arcade.png',
        participantsKo: '전현식 외 3명',
        participantsEn: 'Hyunsik Jeon and 3 others',
        detailKo: {
            overview: '크레이지 아케이드 리메이크라는 "재미있는 껍데기" 아래에서 실시간 시스템 설계를 제대로 연습한 프로젝트. REST API만으로는 동기화할 수 없는 플레이어 간 상태 — 폭탄 설치, 폭발 판정, 방 입장/퇴장 — 을 WebSocket으로 어떻게 일관되게 다룰지가 전부였습니다. React 프론트와 FastAPI + MySQL 백엔드를 실시간 채널로 엮어 보며 "실시간"이라는 단어의 무게를 체감한 프로젝트입니다.',
            features: [
                'WebSocket 기반 실시간 게임 상태 동기화',
                '로비 → 대기방 → 게임방 3단계 방 시스템',
                '실시간 채팅 기능 (채팅방 WebSocket)',
                '물폭탄 설치 및 폭발 범위 계산 게임 로직',
                '아이템 (스피드, 폭탄 수, 폭발 반경) 시스템',
                'MySQL + SQLAlchemy 유저 및 방 데이터 관리',
                'FastAPI CORS 처리 및 REST API 엔드포인트',
            ],
            techDetail: 'React 19, FastAPI, Python, WebSocket, MySQL, SQLAlchemy, Axios',
        },
        detailEn: {
            overview: 'A Crazy Arcade remake that was really an excuse to practice real-time system design. The whole project centered on what REST can\'t do — keeping bomb placement, blast resolution, and room join/leave events consistent between players over WebSocket. Wiring a React frontend to a FastAPI + MySQL backend through a live channel is where the word "real-time" stopped being a buzzword for me.',
            features: [
                'Real-time game state sync via WebSocket',
                '3-tier room system: Lobby → Waiting Room → Game Room',
                'Live in-game chat via dedicated chat WebSocket',
                'Water bomb placement and blast radius game logic',
                'Item system: Speed, Bomb Count, Explosion Range power-ups',
                'MySQL + SQLAlchemy for user and room data management',
                'FastAPI CORS handling and REST API endpoints',
            ],
            techDetail: 'React 19, FastAPI, Python, WebSocket, MySQL, SQLAlchemy, Axios',
        },
    },
    {
        id: 4,
        slug: 'vaccine-daily',
        titleKo: '백신일보',
        titleEn: 'Vaccine Daily Report',
        descKo:
            '핵심 성과: "LLM 한 번 호출하면 끝"이라는 접근을 깨뜨린 프로젝트. Writer → Critic → Editor 3단계 에이전트와 HDBSCAN + ko-sroberta 클러스터링으로 토큰 비용은 줄이고 환각은 잡았으며, 그 위에 GraphRAG로 언론사 논조 분석까지.',
        descEn:
            'Key takeaway: proved that "just call an LLM" is not the answer. Engineered a 3-stage agent pipeline (Writer → Critic → Editor) and replaced naive embedding calls with HDBSCAN + ko-sroberta clustering — dropping token cost while cutting hallucinations. GraphRAG sits on top for outlet-bias analysis.',
        tags: ['React', 'FastAPI', 'GraphRAG', 'Agentic Workflow', 'LLM', 'AWS'],
        link: null,
        github: null,
        video: 'https://youtu.be/MtE-sdo6wY0?si=uVqHrozkFxK2__HM',
        color: '#3b82f6',
        image: '/projects/vaccine-daily.png',
        participantsKo: '전현식 외 2명',
        participantsEn: 'Hyunsik Jeon and 2 others',
        detailKo: {
            overview: '"LLM만 잘 쓰면 해결된다"는 접근의 한계를 제대로 마주한 프로젝트. GPT-4o-mini 하나에 기대는 대신, Writer → Critic → Editor 3단계 에이전트 파이프라인을 설계해 환각을 잡고, HDBSCAN + ko-sroberta로 기사 단위 클러스터링을 돌려 토큰 비용을 체계적으로 줄였습니다. 여기에 GraphRAG로 언론사별 보도 논조까지 분석해, 단순 요약을 넘어 "신뢰할 수 있는 뉴스 리포트"를 자동 생성하는 시스템으로 끌어올렸습니다.',
            features: [
                '[데이터 수집 및 전처리] Selenium 및 BeautifulSoup을 활용하여 10개 언론사 5분 주기 크롤링 및 HDBSCAN + ko-sroberta 기반 토큰 효율적 기사 클러스터링',
                '[AI 에이전트 리포트] Kiwi 형태소 분석과 GPT-4o-mini 기반의 3단계 에이전트 파이프라인(Writer → Critic → Editor)을 통한 환각 방지 및 리포트 작성',
                '[논조 분석 (GraphRAG)] Entity-Relation 트리플 추출 및 지식 그래프 구축을 통한 개별 언론사별 보도 논조 및 경향 분석 시각화',
                '[개인화 지표] 사용자 구독 키워드 및 열람 데이터를 기반으로 한 다기준 추천 스코어링 및 D3 워드클라우드 시각화',
                '[기타] 문장 임베딩 코사인 유사도 인용 검증, 독자 인구통계 대시보드(Recharts) 및 Web Speech API 기반 TTS',
            ],
            techDetail: 'React 18, FastAPI, PostgreSQL 15, ChromaDB, GPT-4o-mini, ko-sroberta, HDBSCAN, Docker Compose, AWS EC2',
        },
        detailEn: {
            overview: 'This project is where I hit the ceiling of "just prompt an LLM better." Instead of leaning on GPT-4o-mini alone, I designed a 3-stage agent pipeline — Writer → Critic → Editor — to catch hallucinations, and layered HDBSCAN + ko-sroberta clustering to cut token cost in a principled way. GraphRAG on top analyzes outlet-level reporting bias, pushing the system past "summarization" into trustworthy news reporting.',
            features: [
                '[Data Pipeline] Selenium & BeautifulSoup scraping of 10 outlets every 5 mins with token-efficient clustering via HDBSCAN + ko-sroberta',
                '[AI Agent Pipeline] 3-stage Agentic Workflow (Writer → Critic → Editor) for hallucination-free reporting and verification',
                '[Tone Analysis (GraphRAG)] Knowledge graph construction via Entity-Relation extraction to visualize media outlet reporting bias',
                '[Personalization] Multi-criteria scoring based on keywords and reading history with D3 Word Cloud visualization',
                '[Personalized Recommendations] Multi-criteria scoring based on subscription keywords/history with D3 Word Clouds',
                '[Other] Cosine similarity citation verification, Recharts demographic dashboards, and Web Speech API TTS',
            ],
            techDetail: 'React 18, FastAPI, PostgreSQL 15, ChromaDB, GPT-4o-mini, ko-sroberta, HDBSCAN, Docker Compose, AWS EC2',
        },
    },
    {
        id: 5,
        slug: 'football-ai',
        titleKo: 'EPL 경기 예측 AI',
        titleEn: 'EPL Match Prediction AI',
        descKo:
            '핵심 성과: 단순 모델 앙상블을 넘어 RL 에이전트를 직접 설계해 TensorFlow + XGBoost + LightGBM의 신뢰도 임계값을 자동 튜닝. 그 위에 몬테카를로 + ELO + GNN을 쌓아 EPL 등 주요 리그에서 실제로 칼리브레이션된 예측을 만들어 낸 프로젝트.',
        descEn:
            'Key takeaway: moved past vanilla ensembling by building an RL agent that auto-tunes confidence thresholds across TensorFlow + XGBoost + LightGBM. Stacked Monte Carlo + ELO + GNN on top to produce genuinely calibrated predictions across EPL and other leagues.',
        tags: ['Python', 'TensorFlow', 'Reinforcement Learning', 'Monte Carlo', 'FastAPI', 'AI/ML'],
        link: null,
        github: null,
        color: '#ef4444',
        image: '/projects/training-day.png',
        images: [
            '/projects/sports-v7.png',
            '/projects/sports-v6.png',
            '/projects/sports-v5.png',
            '/projects/sports-v4.png',
            '/projects/sports-v3.png',
        ],
        participantsKo: '(1인 개발)',
        participantsEn: 'Hyunsik Jeon (Personal Use)',
        detailKo: {
            overview: '"모델을 더 많이 쌓으면 정확도가 올라간다"는 통상적 가정을 넘어서기 위해 RL 에이전트를 직접 설계한 프로젝트입니다. TensorFlow DL + XGBoost + LightGBM의 출력을 단순 평균내는 대신, 강화학습 에이전트가 각 모델의 신뢰도 임계값을 자동으로 튜닝하도록 구성했습니다. 그 위에 몬테카를로 시뮬레이션으로 확률을 칼리브레이션하고, ELO + GNN 기반 팀 전력 지표를 더해, EPL을 중심으로 주요 리그의 경기 예측 신뢰도를 체계적으로 끌어올렸습니다.',
            features: [
                '[Step 1] 데이터 수집: Selenium/BS4 기반 실시간 매치 정보 및 글로벌 배당률 크롤링',
                '[Step 2] 모델 앙상블: TensorFlow DL + XGBoost + LightGBM 트리플 앙상블 아키텍처',
                '[Step 3] 신뢰도 최적화: 강화학습(RL) 에이전트를 통한 모델별 예측 신뢰도 임계값 자동 튜닝',
                '[Step 4] 확률적 추론: 몬테카를로 시뮬레이션 기반의 칼리브레이션 및 결과 확률 산출',
                '[Step 5] 동적 튜닝: 리그별 데이터 휘발성을 반영한 가변 시퀀스 길이 최적화',
                '[Step 6] 전력 분석: ELO 기반 팀 전력 지표 산출 및 GNN 기반 도미넌스 랭킹 적용',
            ],
            techDetail: 'Python, TensorFlow, Reinforcement Learning, Monte Carlo, XGBoost, LightGBM, FastAPI, Pandas',
        },
        detailEn: {
            overview: 'The usual assumption is "stack more models, get more accuracy." This project pushed past that by putting an RL agent in charge of the ensemble itself. Instead of averaging TensorFlow DL + XGBoost + LightGBM outputs, the reinforcement-learning agent auto-tunes the confidence threshold of each model. On top of that sits Monte Carlo simulation for probability calibration and ELO + GNN-based team-strength metrics — producing materially better match predictions across EPL and other major leagues.',
            features: [
                '[Step 1] Data Scrapping: Automated pipeline for match data and global bookmaker odds collection',
                '[Step 2] Predictive Ensembling: Triple architecture — TensorFlow DL + XGBoost + LightGBM',
                '[Step 3] Confidence Optimization: Reinforcement Learning (RL) agent for tuning logical confidence thresholds',
                '[Step 4] Probabilistic Reasoning: Monte Carlo simulation for calibrated outcome probabilities',
                '[Step 5] Dynamic Tuning: Adaptive sequence length optimization based on league-specific volatility',
                '[Step 6] Power Ranking: ELO-based strength metrics and GNN-based dominance analysis',
            ],
            techDetail: 'Python, TensorFlow, Reinforcement Learning, Monte Carlo, XGBoost, LightGBM, FastAPI, Pandas',
        },
    },
    {
        id: 6,
        slug: 'kokkok-garden',
        titleKo: 'KOKKOK Garden (K-뷰티 이커머스)',
        titleEn: 'KOKKOK Garden (K-Beauty E-commerce)',
        descKo:
            '핵심 성과: 바이브 코딩으로 프론트→백엔드→DB→챗봇까지 풀스택을 며칠 만에 세움. Next.js + Supabase + GPT-4o mini로 5개 국어 자동 번역과 AI 챗봇까지 얹어, 기획부터 배포까지의 속도를 증명한 멀티리전 K-뷰티 이커머스.',
        descEn:
            'Key takeaway: stood up a full stack — frontend → backend → DB → chatbot — in days using vibe coding. A multi-region K-beauty e-commerce on Next.js + Supabase with GPT-4o mini translating into 5 languages and an AI chatbot, proving idea-to-deployment speed end-to-end.',
        tags: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS', 'OpenAI', 'Vercel'],
        link: 'https://kokv2.vercel.app',
        github: 'https://github.com/jeonhs9110/kok_v2',
        color: '#ec4899',
        image: null,
        participantsKo: '(1인 개발)',
        participantsEn: 'Hyunsik Jeon (Personal Use)',
        detailKo: {
            overview: '바이브 코딩(vibe coding) 방식으로 기획 → UI → API → DB → 챗봇까지 풀스택을 빠르게 밀어붙여 완성한 한국 화장품 멀티리전 이커머스입니다. 한국 사용자는 구매 가능한 `/kr` 스토어로, 해외 사용자는 뷰잉 + AI 챗봇 중심의 `/gl` 스토어로 자동 분기됩니다. 핵심은 "아이디어에서 배포까지의 속도" — Next.js 16 + Supabase + Tailwind 조합으로 프론트/백엔드/DB/인증/스토리지를 최소한의 보일러플레이트로 엮어 냈고, GPT-4o mini를 unstable_cache에 물려 5개국어(영·중·일·베·태) 번역까지 자연스럽게 얹었습니다.',
            features: [
                '[멀티리전 라우팅] `x-user-country` 헤더 기반 KR/GL 자동 분기 및 6개 언어 라우트',
                '[AI 번역] GPT-4o mini로 상품 데이터 5개국어 자동 번역, unstable_cache로 24시간 캐싱',
                '[AI 챗봇] 글로벌 스토어에 K-뷰티 상담 챗봇 탑재로 해외 뷰잉 고객 경험 강화',
                '[백엔드] Supabase(PostgreSQL + Auth + Storage)로 관리자 인증, 상품 CRUD, 이미지 업로드까지 일원화',
                '[관리자] /admin 대시보드에서 상품·Shorts·미디어 관리, 쿠키 기반 세션 인증',
                '[배포] Vercel 배포 + https://kokv2.vercel.app 운영',
            ],
            techDetail: 'Next.js 16 (App Router), React 19, TypeScript 5, Tailwind CSS 4, Supabase, OpenAI GPT-4o mini, Embla Carousel, Vercel',
        },
        detailEn: {
            overview: 'A multi-region K-beauty e-commerce prototype built in "vibe coding" mode — pushing frontend, backend, DB, and an AI chatbot to production in days instead of weeks. Korean users are routed to a purchasable `/kr` store; international users land on a viewing-only `/gl` store centered on an AI chatbot. The real point of this project was speed from idea to deploy: Next.js 16 + Supabase + Tailwind handled front/back/DB/auth/storage with minimal boilerplate, and GPT-4o mini behind `unstable_cache` layered on 5-language translation (EN/CN/JP/VN/TH) almost for free.',
            features: [
                '[Multi-region routing] Auto split between KR and GL stores via `x-user-country`, with six language routes',
                '[AI translation] GPT-4o mini translates product data into 5 languages, cached for 24h via `unstable_cache`',
                '[AI chatbot] K-beauty consultation chatbot embedded in the GL store to augment viewing-only UX',
                '[Backend] Supabase (PostgreSQL + Auth + Storage) unifies admin auth, product CRUD, and image upload',
                '[Admin] `/admin` dashboard for products, Shorts, and media with cookie-based session auth',
                '[Deploy] Live on Vercel at https://kokv2.vercel.app',
            ],
            techDetail: 'Next.js 16 (App Router), React 19, TypeScript 5, Tailwind CSS 4, Supabase, OpenAI GPT-4o mini, Embla Carousel, Vercel',
        },
    },
    {
        id: 7,
        slug: 'aiim',
        titleKo: 'AIIM — AI 인플루언서 매칭',
        titleEn: 'AIIM — AI Influencer Matching',
        descKo:
            '핵심 성과: Playwright + Reddit API로 인플루언서 데이터를 수집하고, LLM 추론으로 브랜드 적합도를 자동 매칭하는 파이프라인을 설계. "어떤 브랜드에 어떤 인플루언서가 어울리는가"를 사람의 감이 아니라 스크래핑 + LLM 추론으로 풀어낸 프로젝트.',
        descEn:
            'Key takeaway: designed a pipeline that scrapes influencer signal with Playwright + Reddit APIs and uses LLM reasoning to match them to brands. Replacing gut-feeling influencer matching with a scraping + LLM reasoning system.',
        tags: ['Next.js', 'TypeScript', 'Playwright', 'LLM', 'Reddit API', 'AI/ML'],
        link: null,
        github: 'https://github.com/jeonhs9110/infocrawler',
        color: '#8b5cf6',
        image: null,
        participantsKo: '(1인 개발)',
        participantsEn: 'Hyunsik Jeon (Personal Use)',
        detailKo: {
            overview: 'AIIM(AI Influencer Matching)은 "어떤 브랜드에 어떤 인플루언서가 가장 잘 맞는가"라는 질문을 사람의 감각이 아니라 데이터 + LLM 추론으로 풀기 위해 설계한 프로젝트입니다. Playwright 기반 브라우저 자동화와 Reddit 공개 API(snoowrap)로 인플루언서 및 커뮤니티 시그널을 수집하고, 수집된 프로필과 콘텐츠를 LLM에 태워 브랜드 특성과의 적합도를 점수화·설명합니다. Next.js 16 위에서 수집 파이프라인과 매칭 UI를 하나의 앱으로 묶어 "스크래핑 → 분석 → 추천"의 전체 루프를 단일 서비스로 운영 가능하게 만들었습니다.',
            features: [
                '[데이터 수집] Playwright 기반 동적 페이지 스크래핑 + Reddit 공개 API(snoowrap)로 인플루언서/커뮤니티 신호 수집',
                '[AI 매칭] LLM 기반 추론으로 브랜드 특성 ↔ 인플루언서 콘텐츠 적합도 점수 및 근거 자동 생성',
                '[DM 로그] `dm-log` 모듈로 아웃리치 기록 및 상태 추적',
                '[전체 파이프라인] 수집 → 정규화 → LLM 분석 → 추천을 Next.js 앱 한 곳에서 운영',
                '[타입 안정성] TypeScript + Tailwind CSS 4로 유지 보수 가능한 프론트/백 구조',
            ],
            techDetail: 'Next.js 16, React 19, TypeScript, Tailwind CSS 4, Playwright, snoowrap (Reddit), LLM SDK, Axios',
        },
        detailEn: {
            overview: 'AIIM (AI Influencer Matching) attacks the question "which influencer actually fits which brand?" with data and LLM reasoning instead of gut feeling. Playwright browser automation plus Reddit\'s public API (via snoowrap) gather influencer and community signal; the collected profiles and content are then fed through an LLM that scores and explains brand-fit with rationale. Sitting on top of Next.js 16, the scraping pipeline and matching UI live inside a single app, so the whole "scrape → analyze → recommend" loop runs as one coherent system.',
            features: [
                '[Data collection] Playwright-driven dynamic scraping + Reddit public API (snoowrap) for influencer and community signal',
                '[AI matching] LLM-based reasoning scores brand traits vs. influencer content and surfaces fit + rationale',
                '[Outreach log] `dm-log` module tracks DM history and status',
                '[End-to-end pipeline] Collection → normalization → LLM analysis → recommendation runs inside one Next.js app',
                '[Type safety] TypeScript + Tailwind CSS 4 for a maintainable front/back structure',
            ],
            techDetail: 'Next.js 16, React 19, TypeScript, Tailwind CSS 4, Playwright, snoowrap (Reddit), LLM SDK, Axios',
        },
    },
    {
        id: 8,
        slug: 'iamx6',
        titleKo: 'IAMX6 — 네이버 블로그 자동화 데스크톱 앱',
        titleEn: 'IAMX6 — Naver Blog Automation Desktop App',
        descKo:
            '핵심 성과: 웹이 아니라 Electron 데스크톱 앱으로 만든 네이버 블로그 성장 자동화 툴. Puppeteer로 브라우저를 제어하고 AI로 상황에 맞는 댓글을 생성하며, 서로이웃 신청·댓글·좋아요·방문 답글·블로그 분석을 하나의 portable .exe로 패키징.',
        descEn:
            'Key takeaway: shipped a Naver blog growth tool as an Electron desktop app (not a web app). Puppeteer drives the browser, AI writes context-aware comments, and mutual-neighbor requests, comments, likes, auto-replies, and blog analytics all ship as one portable .exe.',
        tags: ['Electron', 'Puppeteer', 'Node.js', 'AI/LLM', 'Desktop App', 'Automation'],
        link: null,
        github: null,
        color: '#14b8a6',
        image: null,
        participantsKo: '(1인 개발 — 비공개 저장소)',
        participantsEn: 'Hyunsik Jeon (Solo — Private Repository)',
        detailKo: {
            overview: 'IAMX6는 네이버 블로그 운영자를 위한 Electron 기반 데스크톱 자동화 툴입니다. 웹 서비스 대신 "내 PC에서 도는 한 개의 .exe"로 설계해, 로그인 상태·브라우저 세션·스케줄링을 사용자 로컬에서 유지하고 플랫폼 정책과의 충돌을 최소화했습니다. 내부적으로는 Puppeteer로 실제 브라우저를 구동하며, AI 모델로 포스팅 맥락에 맞는 자연스러운 댓글을 자동 생성합니다. 서로이웃 신청 / 댓글·좋아요 자동화 / 방문당 답글 / 블로그 DNA 분석 / 설정을 5개 탭 UI로 통합했고, electron-builder로 Windows portable .exe와 macOS dmg를 동시 빌드하도록 구성했습니다.',
            features: [
                '[데스크톱 아키텍처] Electron main/preload/renderer 구조로 UI(HTML/CSS/JS)와 자동화 백엔드를 분리',
                '[브라우저 자동화] Puppeteer-core로 실제 네이버 세션을 제어해 서로이웃 신청·댓글·좋아요 자동화',
                '[AI 댓글 생성] 포스팅 내용에 맞춰 AI가 자연스러운 댓글 문구 생성 (친근/공손/짧게 등 말투 선택)',
                '[방문당 답글] 내 블로그 방문자 댓글에 자동으로 답글 작성',
                '[블로그 분석] 블로그 DNA 진단, 키워드 분석, 포스팅 분석 모듈',
                '[배포] electron-builder로 Windows portable .exe 단일 파일 배포 + macOS dmg 지원',
            ],
            techDetail: 'Electron 25, Node.js, Puppeteer-core, HTML/CSS/JS (Renderer), dotenv, electron-builder (Windows portable / macOS dmg)',
        },
        detailEn: {
            overview: 'IAMX6 is an Electron-based desktop automation tool for Naver blog operators. Building it as a local .exe instead of a web service keeps login state, browser session, and scheduling on the user\'s machine and minimizes friction with platform policy. Under the hood, Puppeteer drives a real browser, and an AI model writes context-aware comments tailored to each post. Mutual-neighbor requests, comment/like automation, visitor auto-reply, blog DNA analytics, and settings are unified under a 5-tab UI, and electron-builder produces a Windows portable .exe and macOS dmg from the same codebase.',
            features: [
                '[Desktop architecture] Electron main/preload/renderer split cleanly separates UI (HTML/CSS/JS) from automation backend',
                '[Browser automation] Puppeteer-core drives a real Naver session for mutual-neighbor, commenting, and like automation',
                '[AI comment generation] AI writes natural comments tuned to post context, with tone presets (friendly / polite / short)',
                '[Visitor auto-reply] Automatically replies to comments left on your own posts',
                '[Blog analytics] Blog DNA diagnosis, keyword analysis, and post-level analytics modules',
                '[Distribution] electron-builder packages a single Windows portable .exe plus macOS dmg',
            ],
            techDetail: 'Electron 25, Node.js, Puppeteer-core, HTML/CSS/JS (Renderer), dotenv, electron-builder (Windows portable / macOS dmg)',
        },
    },
];
